//
// org_aiwolf_sharp_NativePlayer.h
//
// Copyright (c) 2016 Takashi OTSUKI
//
// This software is released under the MIT License.
// http://opensource.org/licenses/mit-license.php
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_aiwolf_sharp_NativePlayer */

#ifndef _Included_org_aiwolf_sharp_NativePlayer
#define _Included_org_aiwolf_sharp_NativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    createNativeInstance
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_aiwolf_sharp_NativePlayer_createNativeInstance
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    getNameNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_aiwolf_sharp_NativePlayer_getNameNative
  (JNIEnv *, jobject);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    updateNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_aiwolf_sharp_NativePlayer_updateNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    initializeNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_aiwolf_sharp_NativePlayer_initializeNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    dayStartNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_aiwolf_sharp_NativePlayer_dayStartNative
  (JNIEnv *, jobject);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    talkNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_aiwolf_sharp_NativePlayer_talkNative
  (JNIEnv *, jobject);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    whisperNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_aiwolf_sharp_NativePlayer_whisperNative
  (JNIEnv *, jobject);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    voteNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_aiwolf_sharp_NativePlayer_voteNative
  (JNIEnv *, jobject);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    attackNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_aiwolf_sharp_NativePlayer_attackNative
  (JNIEnv *, jobject);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    divineNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_aiwolf_sharp_NativePlayer_divineNative
  (JNIEnv *, jobject);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    guardNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_aiwolf_sharp_NativePlayer_guardNative
  (JNIEnv *, jobject);

/*
 * Class:     org_aiwolf_sharp_NativePlayer
 * Method:    finishNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_aiwolf_sharp_NativePlayer_finishNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
